### ISSUE TITLE
Return checksum to variable outside closure

### ISSUE THREAD

**Issue by chrisrogersnz** [rnine/Checksum#4]
Hi,

Thanks for the awesome framework. Sorry for the probably very basic question
How can I return a checksum calculated to a variable outside of the closure? 
I can easily calculate the checksum of a file and print the result however I would like to return the results to an array of strings 

Thanks again!

**Comment by rnine** [comment]
> Thanks for the awesome framework. Sorry for the probably very basic question

Thank you!

> How can I return a checksum calculated to a variable outside of the closure?
I can easily calculate the checksum of a file and print the result however I would like to return the results to an array of string

The simplest thing that comes to mind is that your array could be declared as an instance variable in the class you are calling the async checksum api from. Then you can just simply reference it from inside the completion closure. Since the completion closure is always called from the main thread, your code should be able to append to the array without worrying about race conditions.

Finally, figuring out when all your checksums have finished calculating (maybe to trigger some other code that will use these checksums) could be done by simply counting the elements in your checksum array and comparing it against the total you were expecting. This is also something you could do from the completion closure after appending to the array.

Hope this helps!

**Comment by rnine** [comment]
@chrisrogersnz  I went ahead and included support for calculating checksums of arrays of Data and URLs in [1.0-beta1](
https://github.com/rnine/Checksum/releases/tag/1.0-beta1). 

Check the newly added examples in the README file :)
